// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'IconEntypo:images': typeof import('~icons/entypo/images')['default']
    'IconMaterialSymbols:moreVert': typeof import('~icons/material-symbols/more-vert')['default']
    'IconMdi:check': typeof import('~icons/mdi/check')['default']
    'IconMdi:delete': typeof import('~icons/mdi/delete')['default']
    'IconNoto:satelliteAntenna': typeof import('~icons/noto/satellite-antenna')['default']
    'IconUil:locationArrow': typeof import('~icons/uil/location-arrow')['default']
    Mermaid: typeof import('./src/components/Mermaid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
